Feature/clean poetry
noblotni/satellite_transmission pull request #14
Opened 2023-03-07 02:04 UTC by YoanGab

**Clean architecture of the project**

• Divide files in folders
• Update poetry files
• Add requirements.txt
• Add poetry scripts for executable scripts
• Add typing

2023-03-07 06:47 UTC, noblotni requested changes
Le code est mieux. La nouvelle organisation est pas mal. Les petits changements que j'ai signalés doivent être faits impérativement. Et selon moi, `app` n'est pas un bon nom de package. Je trouvais `satellite_transmission` bien mieux. Il faudrait au moins un nom avec plus de sens que `app`.

2023-03-07 06:47 UTC, noblotni commented on app/main.py
> +"""Run the optimization algorithm."""
Le nom de ce fichier doit être `__main__.py` et pas `main`.

2023-03-07 06:47 UTC, noblotni commented on requirements.txt
> +cloudpickle==2.2.1 ; python_version >= "3.9" and python_version < "3.11"
A quoi sert un requirements.txt si on a un fichier pyproject.toml. Ce dernier récaptitule déjà les dépedances du projet. Il ya redondance. Ce fichier requirements devrait être supprimé.

2023-03-07 10:29 UTC, YoanGab commented on app/main.py
> +"""Run the optimization algorithm."""
Je vois pas l'intérêt dans notre cas avec l'usage de poetry pour les scripts d'utiliser un module et donc un fichier __main__.py.
D'ailleurs je pensais qu'il faudrait renommer ce fichier avec un nom plus explicite pour expliquer qu'il run un de nos agents sur une instance, exemple run_agent.py.

2023-03-07 10:31 UTC, YoanGab commented on requirements.txt
> +cloudpickle==2.2.1 ; python_version >= "3.9" and python_version < "3.11"
Le requirements permet à quelqu'un qui n'a pas poetry de pouvoir installer le projet et de pouvoir s'en servir sans soucis, et je ne pense qu'il fait doublon car il peut très facilement être automatisable pour être sur qu'il soit à jour.
J'ai l'habitude de faire ça car j'ai remarqué qu'énormément de librairies utilisent un fichier pyproject.toml et un fichier requirements.txt.

2023-03-07 11:54 UTC, noblotni commented on requirements.txt
> +cloudpickle==2.2.1 ; python_version >= "3.9" and python_version < "3.11"
La commande `pip install .` fonctionne avec un fichier pyproject.toml que tu aies poetry ou non. `poetry` ne sert qu'à gérer les dépendances du projet et est nécessaire que si quelqu'un contribue à ce projet. POur contribuer, il suffit d'imposer d'utiliser `poetry`. Le fichier `requirements.txt` fait vraiment doublon.

2023-03-07 12:00 UTC, noblotni commented on app/main.py
> +"""Run the optimization algorithm."""
Tu peux peut-être m'apprendre des choses sur l'utilisation de poetry pour les scripts. Je ne l'utilise que pour gérer les dépendances du projet ici. 
Le fichier `__main__.py` est nécessaire (avec cette orthographe) car on a une structure de package dont ce fichier est le point d'entrée. Le fichier contient l'interface en ligne de commande qui gère l'ensemble du package. Cette structure est assez répandue. Je suis un grand fan des CLI et je suis sous Linux. Cette interface me facilite vraiment la vie. 
D'ailleurs la commande pour la lancer est `python -m satellite_rl`. C'est indispensable que le nom de ce fichier reste inchangé.

2023-03-07 12:02 UTC, noblotni commented on pyproject.toml
> +name = "satellite_rl"
Bon nom de package.

2023-03-07 12:08 UTC, noblotni requested changes

2023-03-07 12:08 UTC, noblotni commented on satellite_rl/analyze_actor_critic.py
>  import pandas as pd
Ce fichier devrait être dans un dossier `scripts` à part de `satellite_rl`. Ce code ne s'intègre pas vraiment dans le package pour le moment. Je pourrai le faire dans une autre PR.

2023-03-07 12:08 UTC, noblotni commented on satellite_rl/generate_easy_instances.py
>  def main() -> None:
Pareil que pour `analyze_actor_critic.py`.

2023-03-07 12:08 UTC, noblotni commented on satellite_rl/main.py
> +from satellite_rl.reinforcement_learning.agents.actor_critic import run_actor_critic
Pareil que pour `analyze_actor_critic.py`.

2023-03-07 12:08 UTC, noblotni commented on satellite_rl/main.py
> +from satellite_rl.report import generate_solution_report
Il faut vraiment renommer ce fichier `__main__.py`. Sinon on ne pourra pas exécuter la CLI avec `python -m satellite_rl`.

2023-03-08 13:43 UTC, noblotni requested changes
Le fichier `config.py` devrait être dans le dossier du package.

2023-03-09 16:06 UTC, noblotni approved these changes

2023-03-09 16:36 UTC, merged